### ISSUE TITLE
 build weather application using web-development

### ISSUE THREAD

**Issue by hackelite01** [hackelite01/hacktoberfest2024#1]

**Comment by divyaaa16** [comment]
can you please assign this project to me?

**Comment by shivigoyal4321** [comment]
can u assign me this @hackelite01

**Comment by 2021eo3ar** [comment]
@hackelite01 could you please assign this issue to me also with hacktoberfest label, I can do it too.

**Comment by 2021eo3ar** [comment]
Could you please lable this as `hactoberfest2024` and `hactoberfest`

**Comment by 2021eo3ar** [comment]
Hey @hackelite01 I have Raised a PR for weather Application, kindly mark the issue as `hacktoberFest`, and read the description of 
PR for running the app correctly, Here is the screen shot of that Application:-
![Screenshot 2024-10-14 233856](https://github.com/user-attachments/assets/21045aec-156c-426a-8571-ab31525108cf)

**Comment by divyaaa16** [comment]
please label this hactoberfest2024 and hactoberfest
