### ISSUE TITLE
to-do list application using Flask

### ISSUE THREAD

**Issue by hackelite01** [hackelite01/hacktoberfest2024#3]

**Comment by Ruksina01** [comment]
Hello @hackelite01 ,
I am interested in this issue and would love to contribute. Could you please assign it to me? Additionally, please tag it with Hacktoberfest.

**Comment by Ruksina01** [comment]
hey @hackelite01 , 
Thanks for assigning me this.
I wanted to ask what kind of functionalities it should contain. can you give me a brief explanation on that.

**Comment by hackelite01** [comment]
### Functionalities of a To-Do List Application using Flask
Based on typical features and the discussion in issue [#3](https://github.com/hackelite01/hacktoberfest2024/issues/3), here are some common functionalities that a to-do list application using Flask should contain:

- **User Authentication:** Allow users to create accounts and log in to manage their personal to-do lists.
- **Create, Read, Update, Delete (CRUD) Operations:** Users should be able to add new tasks, view existing tasks, update task details, and delete tasks.
- **Task Status:** Mark tasks as complete or incomplete.
- **Task Prioritization:** Assign priority levels to tasks (e.g., high, medium, low).
- **Due Dates:** Set and manage due dates for tasks.
- **Search and Filter:** Allow users to search for tasks and filter them based on status, priority, and due date.
- **Notifications:** Send reminders or notifications for upcoming or overdue tasks.

These functionalities provide a solid foundation for a to-do list application and can be expanded based on user feedback and additional requirements.

**Comment by Ruksina01** [comment]
Hey @hackelite01 , 
can you check my repository for todo-list app, I added that i my own if that's okay with you. I can fork your repo and then add there.

**Comment by hackelite01** [comment]
sure

**Comment by Ruksina01** [comment]
@hackelite01 
have you checked that? 
And also, please add the tag of hacktoberfest-accepted it would be really helpful.
